
server:
  port: ${tomcat.port}
  servlet:
    context-path: /sdk-front-debug
  tomcat:
    max-connections: 150

properties:
  logback:
    path: ${logback.path}
#参数
spring:
  datasource:
    url: jdbc:mysql://${datasource.ip}:${datasource.port}/${datasource.db-name}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.avalon.sdk.paycenter.model,com.avalon.sdk.usercenter.model
  configuration:
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto